/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_12 (
    input z,
    input v,
    input n,
    input [5:0] alufn_signal,
    output reg cmp
  );
  
  
  
  wire [1-1:0] M_mux_4_out;
  reg [1-1:0] M_mux_4_s0;
  reg [1-1:0] M_mux_4_s1;
  reg [4-1:0] M_mux_4_in;
  mux_4_16 mux_4 (
    .s0(M_mux_4_s0),
    .s1(M_mux_4_s1),
    .in(M_mux_4_in),
    .out(M_mux_4_out)
  );
  
  always @* begin
    M_mux_4_s0 = alufn_signal[1+0-:1];
    M_mux_4_s1 = alufn_signal[2+0-:1];
    M_mux_4_in[1+0-:1] = z;
    M_mux_4_in[2+0-:1] = n ^ v;
    M_mux_4_in[3+0-:1] = z | (n ^ v);
    cmp = M_mux_4_out;
  end
endmodule
