/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rotator_14 (
    input [15:0] a,
    input [3:0] b,
    input [5:0] alufn_signal,
    output reg [15:0] out
  );
  
  
  
  wire [16-1:0] M_rotator_out;
  reg [16-1:0] M_rotator_a;
  reg [4-1:0] M_rotator_b;
  reg [6-1:0] M_rotator_alufn_signal;
  x_bit_rotator_26 rotator (
    .a(M_rotator_a),
    .b(M_rotator_b),
    .alufn_signal(M_rotator_alufn_signal),
    .out(M_rotator_out)
  );
  
  always @* begin
    M_rotator_a = a;
    M_rotator_alufn_signal = alufn_signal;
    M_rotator_b = b;
    out = M_rotator_out;
  end
endmodule
