/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module x_bit_shifter_29 (
    input [31:0] a,
    input [4:0] b,
    input [5:0] alufn_signal,
    output reg [31:0] out
  );
  
  
  
  wire [(6'h20+0)-1:0] M_mux_2_16_out;
  reg [(6'h20+0)-1:0] M_mux_2_16_s0;
  reg [(6'h20+0)-1:0] M_mux_2_16_g0;
  reg [(6'h20+0)-1:0] M_mux_2_16_g1;
  
  genvar GEN_mux_2_160;
  generate
  for (GEN_mux_2_160=0;GEN_mux_2_160<6'h20;GEN_mux_2_160=GEN_mux_2_160+1) begin: mux_2_16_gen_0
    mux_2_25 mux_2_16 (
      .s0(M_mux_2_16_s0[GEN_mux_2_160*(1)+(1)-1-:(1)]),
      .g0(M_mux_2_16_g0[GEN_mux_2_160*(1)+(1)-1-:(1)]),
      .g1(M_mux_2_16_g1[GEN_mux_2_160*(1)+(1)-1-:(1)]),
      .out(M_mux_2_16_out[GEN_mux_2_160*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  wire [(6'h20+0)-1:0] M_mux_2_8_out;
  reg [(6'h20+0)-1:0] M_mux_2_8_s0;
  reg [(6'h20+0)-1:0] M_mux_2_8_g0;
  reg [(6'h20+0)-1:0] M_mux_2_8_g1;
  
  genvar GEN_mux_2_80;
  generate
  for (GEN_mux_2_80=0;GEN_mux_2_80<6'h20;GEN_mux_2_80=GEN_mux_2_80+1) begin: mux_2_8_gen_0
    mux_2_25 mux_2_8 (
      .s0(M_mux_2_8_s0[GEN_mux_2_80*(1)+(1)-1-:(1)]),
      .g0(M_mux_2_8_g0[GEN_mux_2_80*(1)+(1)-1-:(1)]),
      .g1(M_mux_2_8_g1[GEN_mux_2_80*(1)+(1)-1-:(1)]),
      .out(M_mux_2_8_out[GEN_mux_2_80*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  wire [(6'h20+0)-1:0] M_mux_2_4_out;
  reg [(6'h20+0)-1:0] M_mux_2_4_s0;
  reg [(6'h20+0)-1:0] M_mux_2_4_g0;
  reg [(6'h20+0)-1:0] M_mux_2_4_g1;
  
  genvar GEN_mux_2_40;
  generate
  for (GEN_mux_2_40=0;GEN_mux_2_40<6'h20;GEN_mux_2_40=GEN_mux_2_40+1) begin: mux_2_4_gen_0
    mux_2_25 mux_2_4 (
      .s0(M_mux_2_4_s0[GEN_mux_2_40*(1)+(1)-1-:(1)]),
      .g0(M_mux_2_4_g0[GEN_mux_2_40*(1)+(1)-1-:(1)]),
      .g1(M_mux_2_4_g1[GEN_mux_2_40*(1)+(1)-1-:(1)]),
      .out(M_mux_2_4_out[GEN_mux_2_40*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  wire [(6'h20+0)-1:0] M_mux_2_2_out;
  reg [(6'h20+0)-1:0] M_mux_2_2_s0;
  reg [(6'h20+0)-1:0] M_mux_2_2_g0;
  reg [(6'h20+0)-1:0] M_mux_2_2_g1;
  
  genvar GEN_mux_2_20;
  generate
  for (GEN_mux_2_20=0;GEN_mux_2_20<6'h20;GEN_mux_2_20=GEN_mux_2_20+1) begin: mux_2_2_gen_0
    mux_2_25 mux_2_2 (
      .s0(M_mux_2_2_s0[GEN_mux_2_20*(1)+(1)-1-:(1)]),
      .g0(M_mux_2_2_g0[GEN_mux_2_20*(1)+(1)-1-:(1)]),
      .g1(M_mux_2_2_g1[GEN_mux_2_20*(1)+(1)-1-:(1)]),
      .out(M_mux_2_2_out[GEN_mux_2_20*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  wire [(6'h20+0)-1:0] M_mux_2_1_out;
  reg [(6'h20+0)-1:0] M_mux_2_1_s0;
  reg [(6'h20+0)-1:0] M_mux_2_1_g0;
  reg [(6'h20+0)-1:0] M_mux_2_1_g1;
  
  genvar GEN_mux_2_10;
  generate
  for (GEN_mux_2_10=0;GEN_mux_2_10<6'h20;GEN_mux_2_10=GEN_mux_2_10+1) begin: mux_2_1_gen_0
    mux_2_25 mux_2_1 (
      .s0(M_mux_2_1_s0[GEN_mux_2_10*(1)+(1)-1-:(1)]),
      .g0(M_mux_2_1_g0[GEN_mux_2_10*(1)+(1)-1-:(1)]),
      .g1(M_mux_2_1_g1[GEN_mux_2_10*(1)+(1)-1-:(1)]),
      .out(M_mux_2_1_out[GEN_mux_2_10*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    M_mux_2_16_s0 = {6'h20{b[4+0-:1]}};
    M_mux_2_8_s0 = {6'h20{b[3+0-:1]}};
    M_mux_2_4_s0 = {6'h20{b[2+0-:1]}};
    M_mux_2_2_s0 = {6'h20{b[1+0-:1]}};
    M_mux_2_1_s0 = {6'h20{b[0+0-:1]}};
    M_mux_2_16_g0 = a;
    M_mux_2_8_g0 = M_mux_2_16_out;
    M_mux_2_4_g0 = M_mux_2_8_out;
    M_mux_2_2_g0 = M_mux_2_4_out;
    M_mux_2_1_g0 = M_mux_2_2_out;
    
    case ({alufn_signal[1+0-:1], alufn_signal[0+0-:1]})
      2'h0: begin
        M_mux_2_16_g1 = {a[0+15-:16], 16'h0000};
        M_mux_2_8_g1 = {M_mux_2_16_out[0+23-:24], 8'h00};
        M_mux_2_4_g1 = {M_mux_2_8_out[0+27-:28], 4'h0};
        M_mux_2_2_g1 = {M_mux_2_4_out[0+29-:30], 2'h0};
        M_mux_2_1_g1 = {M_mux_2_2_out[0+30-:31], 1'h0};
      end
      2'h1: begin
        M_mux_2_16_g1 = {16'h0000, a[16+15-:16]};
        M_mux_2_8_g1 = {8'h00, M_mux_2_16_out[8+23-:24]};
        M_mux_2_4_g1 = {4'h0, M_mux_2_8_out[4+27-:28]};
        M_mux_2_2_g1 = {2'h0, M_mux_2_4_out[2+29-:30]};
        M_mux_2_1_g1 = {1'h0, M_mux_2_2_out[1+30-:31]};
      end
      2'h3: begin
        M_mux_2_16_g1 = {{5'h10{a[31+0-:1]}}, a[16+15-:16]};
        M_mux_2_8_g1 = {{4'h8{a[31+0-:1]}}, M_mux_2_16_out[8+23-:24]};
        M_mux_2_4_g1 = {{3'h4{a[31+0-:1]}}, M_mux_2_8_out[4+27-:28]};
        M_mux_2_2_g1 = {{2'h2{a[31+0-:1]}}, M_mux_2_4_out[2+29-:30]};
        M_mux_2_1_g1 = {a[31+0-:1], M_mux_2_2_out[1+30-:31]};
      end
      default: begin
        M_mux_2_16_g1 = 32'h00000000;
        M_mux_2_8_g1 = 32'h00000000;
        M_mux_2_4_g1 = 32'h00000000;
        M_mux_2_2_g1 = 32'h00000000;
        M_mux_2_1_g1 = 32'h00000000;
      end
    endcase
    out = (alufn_signal[0+1-:2] == 4'ha) ? 32'h00000000 : M_mux_2_1_out;
  end
endmodule
