/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module autotester_rom_22 (
    input [5:0] test,
    output reg [15:0] auto_ans,
    output reg [15:0] auto_a,
    output reg [15:0] auto_b,
    output reg [5:0] auto_alufn
  );
  
  
  
  localparam Z_A = 16'h0c2b;
  
  localparam Z_B = 16'h0000;
  
  localparam Z = 16'h0c2b;
  
  localparam I_A = 16'h0000;
  
  localparam I_B = 16'h0c2b;
  
  localparam I = 16'h0c2b;
  
  localparam II_A = 16'h0c2b;
  
  localparam II_B = 16'h13d7;
  
  localparam II = 16'h2002;
  
  localparam III_A = 16'h7fff;
  
  localparam III_B = 16'h7fff;
  
  localparam III = 16'hfffe;
  
  localparam IV_A = 16'h13d7;
  
  localparam IV_B = 16'h0000;
  
  localparam IV = 16'h13d7;
  
  localparam V_A = 16'h0000;
  
  localparam V_B = 16'h13d7;
  
  localparam V = 16'hec29;
  
  localparam VI_A = 16'h13d7;
  
  localparam VI_B = 16'h3c2a;
  
  localparam VI = 16'hd7ad;
  
  localparam VII_A = 16'h0000;
  
  localparam VII_B = 16'h7fff;
  
  localparam VII = 16'h8001;
  
  localparam VIII_A = 16'h34d3;
  
  localparam VIII_B = 16'h0000;
  
  localparam VIII = 16'h0000;
  
  localparam IX_A = 16'h34d3;
  
  localparam IX_B = 16'h0001;
  
  localparam IX = 16'h34d3;
  
  localparam X_A = 16'h34d3;
  
  localparam X_B = 16'h59ad;
  
  localparam X = 16'h0d97;
  
  localparam XI_A = 16'hff0f;
  
  localparam XI_B = 16'hf00a;
  
  localparam XI = 16'h0696;
  
  localparam XII_A = 16'hd9ad;
  
  localparam XII_B = 16'h0000;
  
  localparam XII = 16'h0000;
  
  localparam XIII_A = 16'hd9ad;
  
  localparam XIII_B = 16'hffff;
  
  localparam XIII = 16'hd9ad;
  
  localparam XIV_A = 16'hd9ad;
  
  localparam XIV_B = 16'hd9ad;
  
  localparam XIV = 16'hd9ad;
  
  localparam XV_A = 16'hd9ad;
  
  localparam XV_B = 16'h2652;
  
  localparam XV = 16'h0000;
  
  localparam XVI_A = 16'hd9ad;
  
  localparam XVI_B = 16'h0000;
  
  localparam XVI = 16'hd9ad;
  
  localparam XVII_A = 16'hd9ad;
  
  localparam XVII_B = 16'hffff;
  
  localparam XVII = 16'hffff;
  
  localparam XVIII_A = 16'hd9ad;
  
  localparam XVIII_B = 16'hd9ad;
  
  localparam XVIII = 16'hd9ad;
  
  localparam XIX_A = 16'hd9ad;
  
  localparam XIX_B = 16'h0000;
  
  localparam XIX = 16'hd9ad;
  
  localparam XX_A = 16'hd9ad;
  
  localparam XX_B = 16'hd9ad;
  
  localparam XX = 16'h0000;
  
  localparam XXI_A = 16'hd9ad;
  
  localparam XXI_B = 16'h2652;
  
  localparam XXI = 16'hffff;
  
  localparam XXII_A = 16'hd9ad;
  
  localparam XXII_B = 16'h0000;
  
  localparam XXII = 16'hd9ad;
  
  localparam XXIII_A = 16'h0029;
  
  localparam XXIII_B = 16'h0002;
  
  localparam XXIII = 16'h00a4;
  
  localparam XXIV_A = 16'h0029;
  
  localparam XXIV_B = 16'h0000;
  
  localparam XXIV = 16'h0029;
  
  localparam XXV_A = 16'h0029;
  
  localparam XXV_B = 16'h000f;
  
  localparam XXV = 16'h8000;
  
  localparam XXVI_A = 16'h0029;
  
  localparam XXVI_B = 16'h0002;
  
  localparam XXVI = 16'h000a;
  
  localparam XXVII_A = 16'h8000;
  
  localparam XXVII_B = 16'h0000;
  
  localparam XXVII = 16'h8000;
  
  localparam XXVIII_A = 16'h8000;
  
  localparam XXVIII_B = 16'h000f;
  
  localparam XXVIII = 16'h0001;
  
  localparam XXIX_A = 16'h5200;
  
  localparam XXIX_B = 16'h0003;
  
  localparam XXIX = 16'h0a40;
  
  localparam XXX_A = 16'hd200;
  
  localparam XXX_B = 16'h0003;
  
  localparam XXX = 16'hfa40;
  
  localparam XXXI_A = 16'h000a;
  
  localparam XXXI_B = 16'h000a;
  
  localparam XXXI = 16'h0001;
  
  localparam XXXII_A = 16'h000a;
  
  localparam XXXII_B = 16'h000b;
  
  localparam XXXII = 16'h0000;
  
  localparam XXXIII_A = 16'h0004;
  
  localparam XXXIII_B = 16'h0008;
  
  localparam XXXIII = 16'h0001;
  
  localparam XXXIV_A = 16'h0004;
  
  localparam XXXIV_B = 16'h0002;
  
  localparam XXXIV = 16'h0000;
  
  localparam XXXV_A = 16'h0004;
  
  localparam XXXV_B = 16'h0004;
  
  localparam XXXV = 16'h0000;
  
  localparam XXXVI_A = 16'h0004;
  
  localparam XXXVI_B = 16'h0008;
  
  localparam XXXVI = 16'h0001;
  
  localparam XXXVII_A = 16'h0004;
  
  localparam XXXVII_B = 16'h0004;
  
  localparam XXXVII = 16'h0001;
  
  localparam XXXVIII_A = 16'h0004;
  
  localparam XXXVIII_B = 16'h0002;
  
  localparam XXXVIII = 16'h0000;
  
  localparam XXXIX_A = 16'h8421;
  
  localparam XXXIX_B = 16'h0000;
  
  localparam XXXIX = 16'h8421;
  
  localparam XXXX_A = 16'h8421;
  
  localparam XXXX_B = 16'h0008;
  
  localparam XXXX = 16'h2184;
  
  localparam XXXXI_A = 16'h1248;
  
  localparam XXXXI_B = 16'h0000;
  
  localparam XXXXI = 16'h1248;
  
  localparam XXXXII_A = 16'h1248;
  
  localparam XXXXII_B = 16'h0008;
  
  localparam XXXXII = 16'h4812;
  
  localparam ADD = 6'h00;
  
  localparam SUB = 6'h01;
  
  localparam MUL = 6'h02;
  
  localparam AND = 6'h18;
  
  localparam OR = 6'h1e;
  
  localparam XOR = 6'h16;
  
  localparam A = 6'h1a;
  
  localparam SHL = 6'h20;
  
  localparam SHR = 6'h23;
  
  localparam SRA = 6'h23;
  
  localparam CMPEQ = 6'h33;
  
  localparam CMPLT = 6'h35;
  
  localparam CMPLE = 6'h37;
  
  localparam RTL = 6'h28;
  
  localparam RTR = 6'h2c;
  
  always @* begin
    
    case (test)
      6'h00: begin
        auto_a = 16'h0c2b;
        auto_b = 16'h0000;
        auto_alufn = 6'h00;
        auto_ans = 16'h0c2b;
      end
      6'h01: begin
        auto_a = 16'h0000;
        auto_b = 16'h0c2b;
        auto_alufn = 6'h00;
        auto_ans = 16'h0c2b;
      end
      6'h02: begin
        auto_a = 16'h0c2b;
        auto_b = 16'h13d7;
        auto_alufn = 6'h00;
        auto_ans = 16'h2002;
      end
      6'h03: begin
        auto_a = 16'h7fff;
        auto_b = 16'h7fff;
        auto_alufn = 6'h00;
        auto_ans = 16'hfffe;
      end
      6'h04: begin
        auto_a = 16'h13d7;
        auto_b = 16'h0000;
        auto_alufn = 6'h01;
        auto_ans = 16'h13d7;
      end
      6'h05: begin
        auto_a = 16'h0000;
        auto_b = 16'h13d7;
        auto_alufn = 6'h01;
        auto_ans = 16'hec29;
      end
      6'h06: begin
        auto_a = 16'h13d7;
        auto_b = 16'h3c2a;
        auto_alufn = 6'h01;
        auto_ans = 16'hd7ad;
      end
      6'h07: begin
        auto_a = 16'h0000;
        auto_b = 16'h7fff;
        auto_alufn = 6'h01;
        auto_ans = 16'h8001;
      end
      6'h08: begin
        auto_a = 16'h34d3;
        auto_b = 16'h0000;
        auto_alufn = 6'h02;
        auto_ans = 16'h0000;
      end
      6'h09: begin
        auto_a = 16'h34d3;
        auto_b = 16'h0001;
        auto_alufn = 6'h02;
        auto_ans = 16'h34d3;
      end
      6'h0a: begin
        auto_a = 16'h34d3;
        auto_b = 16'h59ad;
        auto_alufn = 6'h02;
        auto_ans = 16'h0d97;
      end
      6'h0b: begin
        auto_a = 16'hff0f;
        auto_b = 16'hf00a;
        auto_alufn = 6'h02;
        auto_ans = 16'h0696;
      end
      6'h0c: begin
        auto_a = 16'hd9ad;
        auto_b = 16'h0000;
        auto_alufn = 6'h18;
        auto_ans = 16'h0000;
      end
      6'h0d: begin
        auto_a = 16'hd9ad;
        auto_b = 16'hffff;
        auto_alufn = 6'h18;
        auto_ans = 16'hd9ad;
      end
      6'h0e: begin
        auto_a = 16'hd9ad;
        auto_b = 16'hd9ad;
        auto_alufn = 6'h18;
        auto_ans = 16'hd9ad;
      end
      6'h0f: begin
        auto_a = 16'hd9ad;
        auto_b = 16'h2652;
        auto_alufn = 6'h18;
        auto_ans = 16'h0000;
      end
      6'h10: begin
        auto_a = 16'hd9ad;
        auto_b = 16'h0000;
        auto_alufn = 6'h1e;
        auto_ans = 16'hd9ad;
      end
      6'h11: begin
        auto_a = 16'hd9ad;
        auto_b = 16'hffff;
        auto_alufn = 6'h1e;
        auto_ans = 16'hffff;
      end
      6'h12: begin
        auto_a = 16'hd9ad;
        auto_b = 16'hd9ad;
        auto_alufn = 6'h1e;
        auto_ans = 16'hd9ad;
      end
      6'h13: begin
        auto_a = 16'hd9ad;
        auto_b = 16'h0000;
        auto_alufn = 6'h16;
        auto_ans = 16'hd9ad;
      end
      6'h14: begin
        auto_a = 16'hd9ad;
        auto_b = 16'hd9ad;
        auto_alufn = 6'h16;
        auto_ans = 16'h0000;
      end
      6'h15: begin
        auto_a = 16'hd9ad;
        auto_b = 16'h2652;
        auto_alufn = 6'h16;
        auto_ans = 16'hffff;
      end
      6'h16: begin
        auto_a = 16'hd9ad;
        auto_b = 16'h0000;
        auto_alufn = 6'h1a;
        auto_ans = 16'hd9ad;
      end
      6'h17: begin
        auto_a = 16'h0029;
        auto_b = 16'h0002;
        auto_alufn = 6'h20;
        auto_ans = 16'h00a4;
      end
      6'h18: begin
        auto_a = 16'h0029;
        auto_b = 16'h0000;
        auto_alufn = 6'h20;
        auto_ans = 16'h0029;
      end
      6'h19: begin
        auto_a = 16'h0029;
        auto_b = 16'h000f;
        auto_alufn = 6'h20;
        auto_ans = 16'h8000;
      end
      6'h1a: begin
        auto_a = 16'h0029;
        auto_b = 16'h0002;
        auto_alufn = 6'h23;
        auto_ans = 16'h000a;
      end
      6'h1b: begin
        auto_a = 16'h8000;
        auto_b = 16'h0000;
        auto_alufn = 6'h23;
        auto_ans = 16'h8000;
      end
      6'h1c: begin
        auto_a = 16'h8000;
        auto_b = 16'h000f;
        auto_alufn = 6'h23;
        auto_ans = 16'h0001;
      end
      6'h1d: begin
        auto_a = 16'h5200;
        auto_b = 16'h0003;
        auto_alufn = 6'h23;
        auto_ans = 16'h0a40;
      end
      6'h1e: begin
        auto_a = 16'hd200;
        auto_b = 16'h0003;
        auto_alufn = 6'h23;
        auto_ans = 16'hfa40;
      end
      6'h1f: begin
        auto_a = 16'h000a;
        auto_b = 16'h000a;
        auto_alufn = 6'h33;
        auto_ans = 16'h0001;
      end
      6'h20: begin
        auto_a = 16'h000a;
        auto_b = 16'h000b;
        auto_alufn = 6'h33;
        auto_ans = 16'h0000;
      end
      6'h21: begin
        auto_a = 16'h0004;
        auto_b = 16'h0008;
        auto_alufn = 6'h35;
        auto_ans = 16'h0001;
      end
      6'h22: begin
        auto_a = 16'h0004;
        auto_b = 16'h0002;
        auto_alufn = 6'h35;
        auto_ans = 16'h0000;
      end
      6'h23: begin
        auto_a = 16'h0004;
        auto_b = 16'h0004;
        auto_alufn = 6'h35;
        auto_ans = 16'h0000;
      end
      6'h24: begin
        auto_a = 16'h0004;
        auto_b = 16'h0008;
        auto_alufn = 6'h37;
        auto_ans = 16'h0001;
      end
      6'h25: begin
        auto_a = 16'h0004;
        auto_b = 16'h0004;
        auto_alufn = 6'h37;
        auto_ans = 16'h0001;
      end
      6'h26: begin
        auto_a = 16'h0004;
        auto_b = 16'h0002;
        auto_alufn = 6'h37;
        auto_ans = 16'h0000;
      end
      6'h27: begin
        auto_a = 16'h8421;
        auto_b = 16'h0000;
        auto_alufn = 6'h28;
        auto_ans = 16'h8421;
      end
      6'h28: begin
        auto_a = 16'h8421;
        auto_b = 16'h0008;
        auto_alufn = 6'h28;
        auto_ans = 16'h2184;
      end
      6'h29: begin
        auto_a = 16'h1248;
        auto_b = 16'h0000;
        auto_alufn = 6'h2c;
        auto_ans = 16'h1248;
      end
      6'h2a: begin
        auto_a = 16'h1248;
        auto_b = 16'h0008;
        auto_alufn = 6'h2c;
        auto_ans = 16'h4812;
      end
      default: begin
        auto_a = 16'h0000;
        auto_b = 16'h0000;
        auto_alufn = 16'h0000;
        auto_ans = 16'h0000;
      end
    endcase
  end
endmodule
