/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_11 (
    input [15:0] a,
    input [3:0] b,
    input [5:0] alufn_signal,
    output reg [15:0] shift
  );
  
  
  
  wire [16-1:0] M_shifter_out;
  reg [16-1:0] M_shifter_a;
  reg [4-1:0] M_shifter_b;
  reg [6-1:0] M_shifter_alufn_signal;
  x_bit_shifter_24 shifter (
    .a(M_shifter_a),
    .b(M_shifter_b),
    .alufn_signal(M_shifter_alufn_signal),
    .out(M_shifter_out)
  );
  
  always @* begin
    M_shifter_a = a;
    M_shifter_alufn_signal = alufn_signal;
    M_shifter_b = b;
    shift = M_shifter_out;
  end
endmodule
