/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier_24 (
    input [31:0] a,
    input [31:0] b,
    output reg [31:0] mul
  );
  
  
  
  wire [32-1:0] M_adderarray_out;
  reg [32-1:0] M_adderarray_a;
  reg [32-1:0] M_adderarray_b;
  rca_adderarray_30 adderarray (
    .a(M_adderarray_a),
    .b(M_adderarray_b),
    .out(M_adderarray_out)
  );
  
  always @* begin
    mul = 1'h0;
    M_adderarray_a = a;
    M_adderarray_b = b;
    mul = M_adderarray_out;
  end
endmodule
