/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_15 (
    input [31:0] a,
    input [31:0] b,
    input [5:0] alufn_signal,
    output reg [31:0] out,
    output reg [2:0] zvn
  );
  
  
  
  wire [32-1:0] M_adder_out;
  wire [1-1:0] M_adder_z;
  wire [1-1:0] M_adder_v;
  wire [1-1:0] M_adder_n;
  reg [32-1:0] M_adder_a;
  reg [32-1:0] M_adder_b;
  reg [6-1:0] M_adder_alufn_signal;
  adder_20 adder (
    .a(M_adder_a),
    .b(M_adder_b),
    .alufn_signal(M_adder_alufn_signal),
    .out(M_adder_out),
    .z(M_adder_z),
    .v(M_adder_v),
    .n(M_adder_n)
  );
  
  wire [32-1:0] M_boolean_bool;
  reg [32-1:0] M_boolean_a;
  reg [32-1:0] M_boolean_b;
  reg [6-1:0] M_boolean_alufn_signal;
  boolean_21 boolean (
    .a(M_boolean_a),
    .b(M_boolean_b),
    .alufn_signal(M_boolean_alufn_signal),
    .bool(M_boolean_bool)
  );
  
  wire [32-1:0] M_shifter_shift;
  reg [32-1:0] M_shifter_a;
  reg [5-1:0] M_shifter_b;
  reg [6-1:0] M_shifter_alufn_signal;
  shifter_22 shifter (
    .a(M_shifter_a),
    .b(M_shifter_b),
    .alufn_signal(M_shifter_alufn_signal),
    .shift(M_shifter_shift)
  );
  
  wire [1-1:0] M_compare_cmp;
  reg [1-1:0] M_compare_z;
  reg [1-1:0] M_compare_v;
  reg [1-1:0] M_compare_n;
  reg [6-1:0] M_compare_alufn_signal;
  compare_23 compare (
    .z(M_compare_z),
    .v(M_compare_v),
    .n(M_compare_n),
    .alufn_signal(M_compare_alufn_signal),
    .cmp(M_compare_cmp)
  );
  
  wire [32-1:0] M_multiplier_mul;
  reg [32-1:0] M_multiplier_a;
  reg [32-1:0] M_multiplier_b;
  multiplier_24 multiplier (
    .a(M_multiplier_a),
    .b(M_multiplier_b),
    .mul(M_multiplier_mul)
  );
  
  wire [(6'h20+0)-1:0] M_mux_a_out;
  reg [(6'h20+0)-1:0] M_mux_a_s0;
  reg [(6'h20+0)-1:0] M_mux_a_g0;
  reg [(6'h20+0)-1:0] M_mux_a_g1;
  
  genvar GEN_mux_a0;
  generate
  for (GEN_mux_a0=0;GEN_mux_a0<6'h20;GEN_mux_a0=GEN_mux_a0+1) begin: mux_a_gen_0
    mux_2_25 mux_a (
      .s0(M_mux_a_s0[GEN_mux_a0*(1)+(1)-1-:(1)]),
      .g0(M_mux_a_g0[GEN_mux_a0*(1)+(1)-1-:(1)]),
      .g1(M_mux_a_g1[GEN_mux_a0*(1)+(1)-1-:(1)]),
      .out(M_mux_a_out[GEN_mux_a0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  wire [(6'h20+0)-1:0] M_mux_b_out;
  reg [(6'h20+0)-1:0] M_mux_b_s0;
  reg [(6'h20+0)-1:0] M_mux_b_s1;
  reg [(6'h20+0)*4-1:0] M_mux_b_in;
  
  genvar GEN_mux_b0;
  generate
  for (GEN_mux_b0=0;GEN_mux_b0<6'h20;GEN_mux_b0=GEN_mux_b0+1) begin: mux_b_gen_0
    mux_4_26 mux_b (
      .s0(M_mux_b_s0[GEN_mux_b0*(1)+(1)-1-:(1)]),
      .s1(M_mux_b_s1[GEN_mux_b0*(1)+(1)-1-:(1)]),
      .in(M_mux_b_in[GEN_mux_b0*(3'h4)+(3'h4)-1-:(3'h4)]),
      .out(M_mux_b_out[GEN_mux_b0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  integer i;
  
  always @* begin
    M_mux_b_in = 128'h00000000000000000000000000000000;
    M_adder_a = a;
    M_adder_b = b;
    M_adder_alufn_signal = alufn_signal;
    zvn[0+0-:1] = M_adder_z;
    zvn[1+0-:1] = M_adder_v;
    zvn[2+0-:1] = M_adder_n;
    out = M_adder_out;
    M_compare_z = M_adder_z;
    M_compare_v = M_adder_v;
    M_compare_n = M_adder_n;
    M_compare_alufn_signal = alufn_signal;
    M_boolean_a = a;
    M_boolean_b = b;
    M_boolean_alufn_signal = alufn_signal;
    M_shifter_a = a;
    M_shifter_b = b[0+3-:4];
    M_shifter_alufn_signal = alufn_signal;
    M_multiplier_a = a;
    M_multiplier_b = b;
    M_mux_a_g0 = M_adder_out;
    M_mux_a_g1 = M_multiplier_mul;
    M_mux_a_s0 = {6'h20{alufn_signal[1+0-:1]}};
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      M_mux_b_in[(i)*4+0+0-:1] = M_mux_a_out[(i)*1+0-:1];
      M_mux_b_in[(i)*4+1+0-:1] = M_boolean_bool[(i)*1+0-:1];
      M_mux_b_in[(i)*4+2+0-:1] = M_shifter_shift[(i)*1+0-:1];
      M_mux_b_in[(i)*4+3+0-:1] = (i == 1'h0) ? M_compare_cmp : 1'h0;
    end
    M_mux_b_s0 = {6'h20{alufn_signal[4+0-:1]}};
    M_mux_b_s1 = {6'h20{alufn_signal[5+0-:1]}};
    out = M_mux_b_out;
  end
endmodule
