/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WORDS = MEMORY_SIZE
*/
module instruction_rom_8 (
    input [4:0] addr,
    output reg [31:0] out
  );
  
  localparam WORDS = 6'h20;
  
  
  localparam INSTRUCTIONS = 160'h7be3fffb607f0020643f002090410800c03f0003;
  
  always @* begin
    out = INSTRUCTIONS[(addr)*32+31-:32];
  end
endmodule
