/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module thirtytwobit_rca_28 (
    input [31:0] a,
    input [31:0] b,
    input ci,
    output reg [31:0] s,
    output reg co
  );
  
  
  
  wire [(6'h20+0)-1:0] M_fa_s;
  wire [(6'h20+0)-1:0] M_fa_co;
  reg [(6'h20+0)-1:0] M_fa_a;
  reg [(6'h20+0)-1:0] M_fa_b;
  reg [(6'h20+0)-1:0] M_fa_ci;
  
  genvar GEN_fa0;
  generate
  for (GEN_fa0=0;GEN_fa0<6'h20;GEN_fa0=GEN_fa0+1) begin: fa_gen_0
    full_adder_31 fa (
      .a(M_fa_a[GEN_fa0*(1)+(1)-1-:(1)]),
      .b(M_fa_b[GEN_fa0*(1)+(1)-1-:(1)]),
      .ci(M_fa_ci[GEN_fa0*(1)+(1)-1-:(1)]),
      .s(M_fa_s[GEN_fa0*(1)+(1)-1-:(1)]),
      .co(M_fa_co[GEN_fa0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    M_fa_a = a;
    M_fa_b = b;
    M_fa_ci[0+0-:1] = ci;
    M_fa_ci[1+30-:31] = M_fa_co[0+30-:31];
    s = M_fa_s;
    co = M_fa_co[31+0-:1];
  end
endmodule
